/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RibadoltRouteImport } from './routes/ribadolt'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestimentosIndexRouteImport } from './routes/investimentos.index'
import { Route as InvestimentosSlugRouteImport } from './routes/investimentos.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminObrasRouteImport } from './routes/_authenticated/admin.obras'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminInvestimentosRouteImport } from './routes/_authenticated/admin.investimentos'
import { Route as AuthenticatedAdminDefinicoesRouteImport } from './routes/_authenticated/admin.definicoes'

const RibadoltRoute = RibadoltRouteImport.update({
  id: '/ribadolt',
  path: '/ribadolt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosIndexRoute = InvestimentosIndexRouteImport.update({
  id: '/investimentos/',
  path: '/investimentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosSlugRoute = InvestimentosSlugRouteImport.update({
  id: '/investimentos/$slug',
  path: '/investimentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminObrasRoute = AuthenticatedAdminObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInvestimentosRoute =
  AuthenticatedAdminInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDefinicoesRoute =
  AuthenticatedAdminDefinicoesRouteImport.update({
    id: '/definicoes',
    path: '/definicoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/ribadolt': typeof RibadoltRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/investimentos/$slug': typeof InvestimentosSlugRoute
  '/investimentos/': typeof InvestimentosIndexRoute
  '/admin/definicoes': typeof AuthenticatedAdminDefinicoesRoute
  '/admin/investimentos': typeof AuthenticatedAdminInvestimentosRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/obras': typeof AuthenticatedAdminObrasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/ribadolt': typeof RibadoltRoute
  '/investimentos/$slug': typeof InvestimentosSlugRoute
  '/investimentos': typeof InvestimentosIndexRoute
  '/admin/definicoes': typeof AuthenticatedAdminDefinicoesRoute
  '/admin/investimentos': typeof AuthenticatedAdminInvestimentosRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/obras': typeof AuthenticatedAdminObrasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contactos': typeof ContactosRoute
  '/login': typeof LoginRoute
  '/obras': typeof ObrasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/ribadolt': typeof RibadoltRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/investimentos/$slug': typeof InvestimentosSlugRoute
  '/investimentos/': typeof InvestimentosIndexRoute
  '/_authenticated/admin/definicoes': typeof AuthenticatedAdminDefinicoesRoute
  '/_authenticated/admin/investimentos': typeof AuthenticatedAdminInvestimentosRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/obras': typeof AuthenticatedAdminObrasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contactos'
    | '/login'
    | '/obras'
    | '/quem-somos'
    | '/ribadolt'
    | '/admin'
    | '/investimentos/$slug'
    | '/investimentos/'
    | '/admin/definicoes'
    | '/admin/investimentos'
    | '/admin/leads'
    | '/admin/obras'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contactos'
    | '/login'
    | '/obras'
    | '/quem-somos'
    | '/ribadolt'
    | '/investimentos/$slug'
    | '/investimentos'
    | '/admin/definicoes'
    | '/admin/investimentos'
    | '/admin/leads'
    | '/admin/obras'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contactos'
    | '/login'
    | '/obras'
    | '/quem-somos'
    | '/ribadolt'
    | '/_authenticated/admin'
    | '/investimentos/$slug'
    | '/investimentos/'
    | '/_authenticated/admin/definicoes'
    | '/_authenticated/admin/investimentos'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/obras'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactosRoute: typeof ContactosRoute
  LoginRoute: typeof LoginRoute
  ObrasRoute: typeof ObrasRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RibadoltRoute: typeof RibadoltRoute
  InvestimentosSlugRoute: typeof InvestimentosSlugRoute
  InvestimentosIndexRoute: typeof InvestimentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ribadolt': {
      id: '/ribadolt'
      path: '/ribadolt'
      fullPath: '/ribadolt'
      preLoaderRoute: typeof RibadoltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos/': {
      id: '/investimentos/'
      path: '/investimentos'
      fullPath: '/investimentos/'
      preLoaderRoute: typeof InvestimentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos/$slug': {
      id: '/investimentos/$slug'
      path: '/investimentos/$slug'
      fullPath: '/investimentos/$slug'
      preLoaderRoute: typeof InvestimentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/obras': {
      id: '/_authenticated/admin/obras'
      path: '/obras'
      fullPath: '/admin/obras'
      preLoaderRoute: typeof AuthenticatedAdminObrasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/investimentos': {
      id: '/_authenticated/admin/investimentos'
      path: '/investimentos'
      fullPath: '/admin/investimentos'
      preLoaderRoute: typeof AuthenticatedAdminInvestimentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/definicoes': {
      id: '/_authenticated/admin/definicoes'
      path: '/definicoes'
      fullPath: '/admin/definicoes'
      preLoaderRoute: typeof AuthenticatedAdminDefinicoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDefinicoesRoute: typeof AuthenticatedAdminDefinicoesRoute
  AuthenticatedAdminInvestimentosRoute: typeof AuthenticatedAdminInvestimentosRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminObrasRoute: typeof AuthenticatedAdminObrasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDefinicoesRoute: AuthenticatedAdminDefinicoesRoute,
  AuthenticatedAdminInvestimentosRoute: AuthenticatedAdminInvestimentosRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminObrasRoute: AuthenticatedAdminObrasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactosRoute: ContactosRoute,
  LoginRoute: LoginRoute,
  ObrasRoute: ObrasRoute,
  QuemSomosRoute: QuemSomosRoute,
  RibadoltRoute: RibadoltRoute,
  InvestimentosSlugRoute: InvestimentosSlugRoute,
  InvestimentosIndexRoute: InvestimentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
